### ISSUE TITLE
Spyro: Ripto Quest crashes after the intro logos, no music

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#13]
This is a game from the same series as Spyro Reignited Trilogy from a few years ago, the remake of the even more iconic PS1 games. You wouldn't tell that by how low-budget and apparently stupidly-programmed this game is, not that I could do any better.

I used the Nokia 176x208 version, all other versions require softkey commands or Nokia Sound which I don't think are supported at the moment. In addition IIRC this version is not obfuscated. This version specifically is hard to find, so I'm just gonna say I have an IA upload with various Spyro mobile game versions including ones from the ridiculously unmanageable website archives.

It opens with the correct logos, but without the background music, and then when it's time to display the main menu, it freezes with this thrown into the console:

```
Canvas repaint(): nulljava.lang.NegativeArraySizeException
        at z.Screen.b(Unknown Source)
        at z.Screen.paint(Unknown Source)
        at javax.microedition.lcdui.Canvas.repaint(Canvas.java:167)
        at z.Main.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by AShiningRay** [comment]
Seems pretty similar to something that happens on some Mission Impossible III versions (basically any that's high-end), where it crashes at the intro screens with a ArrayIndexOutOfBoundsException... and i'm pretty sure those two are far from the only games that suffer from issues when trying to paint a PlatformGraphics object.

**Comment by AShiningRay** [comment]
Finally fixed by f47203de740cf645e09a942b5c8c17b7553f69c8. All versions are perfectly fine aside from the K700B one that uses commands and device keys at the same time, and also has a horrendous keyPress() implementation after decompiling.
