### ISSUE TITLE
Turrican (176x208 and 240x320) crashes after the intro logo

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#36]
Error message:
```
Exception in thread "Thread-5" java.lang.NoSuchMethodError: javax.microedition.lcdui.game.Sprite.setRefPixelPosition(II)V
        at com.thq.Turrican.d.a(Unknown Source)
        at com.thq.Turrican.g.a(Unknown Source)
        at com.thq.Turrican.j.paint(Unknown Source)
        at javax.microedition.lcdui.Canvas.repaint(Unknown Source)
        at com.thq.Turrican.j.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
There are some 128x128 versions that work but spam Nokia Sound error messages into the console.

**Comment by TwoSpacesSG** [comment]
I don't know when this happened, but this issue is back with a similar error message.

**Comment by AShiningRay** [comment]
It was caused by this: a6cc9a18ed118d7926f863898e80db9e06b7e146

Not even sure why i removed those in the first place... time to add them again.
